
//参数通信库
#include "Project.h"
#include "Terminal_Uart_AFN04_Paramter.h"



const TerminalParamterLib_TypeDef     TerminalParamterLib[]=
{
	{//终端上行通信口通信参数设置
		ADDR_AFN04F1,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		6,//数据长度
		0,//最大Pn
	},
	{//终端上行通信口无线中继转发设置
		ADDR_AFN04F2,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//主站IP地址和端口
		ADDR_AFN04F3,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		28,//数据长度
		0,//最大Pn
	},
	{//主站电话号码和短信中心号码
		ADDR_AFN04F4,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		16,//数据长度
		0,//最大Pn
	},
	{//终端上行通信消息认证参数
		ADDR_AFN04F5,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		3,//数据长度
		0,//最大Pn
	},
	{//终端组地址
		ADDR_AFN04F6,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
#if (USER/100)==11//吉林系
		32,//数据长度
#else
		16,//数据长度
#endif
		0,//最大Pn
	},
	{//终端IP地址和端口
		ADDR_AFN04F7,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//终端上行通信工作方式（以太专网或虚拟专网）
		ADDR_AFN04F8,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		8,//数据长度
		0,//最大Pn
	},
	{//终端事件记录配置设置
		ADDR_AFN04F9,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		16,//数据长度
		0,//最大Pn
	},
	{//终端电能表／交流采样装置配置参数
		ADDR_AFN04F10,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//终端脉冲配置参数
		ADDR_AFN04F11,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//终端状态量输入参数
		ADDR_AFN04F12,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		2,//数据长度
		0,//最大Pn
	},
	{//终端电压／电流模拟量配置参数
		ADDR_AFN04F13,
		0,//0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//终端总加组配置参数
		ADDR_AFN04F14,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//有功总电能量差动越限事件参数
		ADDR_AFN04F15,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//虚拟专网用户名、密码
		ADDR_AFN04F16,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		64,//数据长度
		0,//最大Pn
	},
	{//终端保安定值
		ADDR_AFN04F17,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		2,//数据长度
		0,//最大Pn
	},
	{//终端功控时段
		ADDR_AFN04F18,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		12,//数据长度
		0,//最大Pn
	},
	{//终端时段功控定值浮动系数
		ADDR_AFN04F19,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		0,//最大Pn
	},
	{//终端月电能量控定值浮动系数
		ADDR_AFN04F20,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		0,//最大Pn
	},
	{//终端电能量费率时段和费率数
		ADDR_AFN04F21,
		0xfc,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		49,//数据长度
		0,//最大Pn
	},
	{//终端电能量费率
		ADDR_AFN04F22,
		0xfc,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//终端催费告警参数
		ADDR_AFN04F23,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		3,//数据长度
		0,//最大Pn
	},
	{//f24
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//测量点基本参数
		ADDR_AFN04F25,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		11,//数据长度
		AFN04F25MaxPn,//最大Pn
	},
	{//测量点限值参数
		ADDR_AFN04F26,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		57,
		AFN04F26MaxPn,//最大Pn
	},
	{//测量点铜损、铁损参数
		ADDR_AFN04F27,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		24,//数据长度
		AFN04F27MaxPn,//最大Pn
	},
	{//测量点功率因数分段限值
		ADDR_AFN04F28,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		4,//数据长度
		AFN04F28MaxPn,//最大Pn
	},
	{//终端当地电能表显示号
		ADDR_AFN04F29,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		12,//数据长度
		AFN04F29MaxPn,//最大Pn
	},
	{//台区集中抄表停抄/投抄设置
		ADDR_AFN04F30,
		0x04,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		AFN04F30MaxPn,//最大Pn
	},
	{//载波从节点附属节点地址
		ADDR_AFN04F31,
		0x04,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		AFN04F31MaxPn,//最大Pn
	},
	{//f32
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//终端抄表运行参数
		ADDR_AFN04F33,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//集中器下行通信模块的参数
		ADDR_AFN04F34,
		0x04,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//台区集中抄表重点户设置
		ADDR_AFN04F35,
#if (USER/100)==10//河北系				
    0x0C,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表	
#else		 
		0x04,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
#endif		
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//终端上行通信流量门限设置
		ADDR_AFN04F36,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		4,//数据长度
		0,//最大Pn
	},
	{//终端级联通信参数
		ADDR_AFN04F37,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//1类数据配置设置
		ADDR_AFN04F38,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//2类数据配置设置
		ADDR_AFN04F39,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//f40
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//时段功控定值
		ADDR_AFN04F41,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		AFN04F41MaxPn,//最大Pn
	},
	{//厂休功控参数
		ADDR_AFN04F42,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		6,//数据长度
		AFN04F42MaxPn,//最大Pn
	},
	{//功率控制的功率计算滑差时间
		ADDR_AFN04F43,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		AFN04F43MaxPn,//最大Pn
	},
	{//营业报停控参数
		ADDR_AFN04F44,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		8,//数据长度
		AFN04F44MaxPn,//最大Pn
	},
	{//功控轮次设定
		ADDR_AFN04F45,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		AFN04F45MaxPn,//最大Pn
	},
	{//月电量控定值
		ADDR_AFN04F46,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		4+1,//数据长度
		AFN04F46MaxPn,//最大Pn
	},
	{//购电量（费）控参数
		ADDR_AFN04F47,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		17,
		AFN04F47MaxPn,//最大Pn
	},
	{//电控轮次设定
		ADDR_AFN04F48,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		AFN04F48MaxPn,//最大Pn
	},
	{//功控告警时间
		ADDR_AFN04F49,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		AFN04F49MaxPn,//最大Pn
	},
	{//50
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//51
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//52
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//53
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//54
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//55
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//56
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//终端声音告警允许∕禁止设置
		ADDR_AFN04F57,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		3,//数据长度
		0,//最大Pn
	},
	{//终端自动保电参数
		ADDR_AFN04F58,
		0x08,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		0,//最大Pn
	},
	{//电能表异常判别阈值设定
		ADDR_AFN04F59,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		5,//数据长度
		0,//最大Pn
	},
	{//谐波限值
		ADDR_AFN04F60,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		6+36+2+36,//数据长度
		0,//最大Pn
	},
#if (MaxDCPn==0)//最大直流模拟量测量点数
	{//直流模拟量接入参数
		0,//ADDR_AFN04F61,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
#else
	{//直流模拟量接入参数
		ADDR_AFN04F61,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,
		0,//最大Pn
	},
#endif
	{//62
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//63
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//64
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//定时上报1类数据任务设置
		ADDR_AFN04F65,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		AFN04F65MaxPn,//最大Pn
	},
	{//定时上报2类数据任务设置
		ADDR_AFN04F66,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		AFN04F66MaxPn,//最大Pn
	},
	{//定时上报1类数据任务启动/停止设置
		ADDR_AFN04F67,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		AFN04F67MaxPn,//最大Pn
	},
	{//定时上报2类数据任务启动/停止设置
		ADDR_AFN04F68,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		AFN04F68MaxPn,//最大Pn
	},
	{//69
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//70
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//71
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//72
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//电容器参数
		ADDR_AFN04F73,
		0x14,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		48,//数据长度
		AFN04F73MaxPn,//最大Pn
	},
	{//电容器投切运行参数
		ADDR_AFN04F74,
		0x14,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		10,//数据长度
		AFN04F74MaxPn,//最大Pn
	},
	{//电容器保护参数
		ADDR_AFN04F75,
		0x14,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		16,//数据长度
		AFN04F75MaxPn,//最大Pn
	},
	{//电容器投切控制方式
		ADDR_AFN04F76,
		0x14,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		AFN04F76MaxPn,//最大Pn
	},
	{//77
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//78
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//79
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//80
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
	},
	{//直流模拟量输入变比
		ADDR_AFN04F81,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		4,//数据长度
		AFN04F81MaxPn,//最大Pn
	},
	{//直流模拟量限值
		ADDR_AFN04F82,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		4,//数据长度
		AFN04F82MaxPn,//最大Pn
	},
	{//直流模拟量冻结参数
		ADDR_AFN04F83,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		AFN04F83MaxPn,//最大Pn
	},
	{//终端通信端口配置参数
		ADDR_AFN04F84,
		0,//0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//85
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//86
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//87
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//88
#if (USER/100)==2//用户标识:山东版
		ADDR_AFN04F88,//电能表资产编号
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		15,//数据长度
		AFN04F88MaxPn,//最大Pn
#else
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
#endif
	},
	{//终端区域码和地址
		ADDR_AFN04F89,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		4,//数据长度
		0,//最大Pn
	},
	{//无线通信参数
		ADDR_AFN04F90,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		2,//数据长度
		0,//最大Pn
	},
	{//终端地理位置信息
		ADDR_AFN04F91,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		10,//数据长度
		0,//最大Pn
	},
	{//92
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//93
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//94
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//95
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//96
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//97 停电数据采集配置参数
		ADDR_AFN04F97,
		0xff,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		5,//数据长度
		0,//最大Pn
	},
	{//98 停电事件甄别限值参数
		ADDR_AFN04F98,
		0xff,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		13,//数据长度
		0,//最大Pn
	},
	{//99
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//100
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//101
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//102
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//103
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//104 曲线冻结密度参数(测量点号)
		ADDR_AFN04F104,
		0xff,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		AFN04F104MaxPn,//最大Pn
	},
	{//105 电能表数据分级归类参数(测量点号)
		ADDR_AFN04F105,
		0xff,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		AFN04F105MaxPn,//最大Pn
	},
	{//106 电能表数据分级参数(数据分级类号)
		ADDR_AFN04F106,
		0xff,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		MDCnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		AFN04F106MaxPn,//最大Pn
	},
	{//107 电能表数据分级周期参数(数据等级号)
		ADDR_AFN04F107,
		0xff,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		MDEnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		2,//数据长度
		AFN04F107MaxPn,//最大Pn
	},
	{//108
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//109
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//110
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//111
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//112
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//113
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//114
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//115
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//116
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//117
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//118
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//119
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//120
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//121
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//122
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//123
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//124
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//125
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//126
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//127
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//128
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//129
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//130
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//131
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//132
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//133
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//134
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//135
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//136
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//137
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//138
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//139
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//140
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//141
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//142
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//143
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//144
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//145
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//146
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//147
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//148
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//149
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//150 测量点状态(只读参数)
		ADDR_AFN04F150,
		0xFF,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		512,//数据长度
		0,//最大Pn
	},
	{//151
//四川用户AFN04F151已单独扩展使用
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//152
	#if (USER/100)==12//用户标识:四川
		//终端手机号码
		ADDR_AFN04F152,
		0xff,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		8,//数据长度
		0,//最大Pn
	#else
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	#endif
	},
	{//153
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//154
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//155
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//156
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//157
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//158
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//159
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//160
	#if (USER/100)==5//用户标识:上海
		//档案完整性比对
		ADDR_DATABUFF,
		0xff,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		2+256,//数据长度
		0,//最大Pn
	#else
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	#endif
	},
	{//161
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//162
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//163
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//164
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//165
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//166
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//167
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//168
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//169
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//170
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//171
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//172
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//173
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//174
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//175
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//176
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//177
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//178
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//179
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//180
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//181
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//182
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//183
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//184
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//185
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//186
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//187
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//188
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//189
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//190
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//191
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//192
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//193
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//194
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//195
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//196
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//197
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//198
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//199
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//200
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//201
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//202
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//203
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//204
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//205
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//206
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//207
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//208
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//209
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//210
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//211
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//212
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//213
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//214
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//215
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//216
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//217
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//218
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//219
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//220
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//221
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//222
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//223
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//224
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//225
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//226
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//227
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//228
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//229
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//230
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//231
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//232
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//233
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//234
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//235
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//236
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//237
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//238
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//239
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//240
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	{//241
	#if (USER/100)==5//用户标识:上海
		ADDR_AFN04F241,
		0xff,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		5,//数据长度
		0,//最大Pn
	#else
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	#endif
	},
	{//242
	#if (USER/100)==5//用户标识:上海
		//终端对电能表抄表机制的参数
		ADDR_AFN04F242,
		0xff,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		0,//最大Pn
	#else
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	#endif
	},
	{//243
	#if (USER/100)==5//用户标识:上海
		//终端手机号码
		ADDR_AFN04F243,
		0xff,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		8,//数据长度
		0,//最大Pn
	#else
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	#endif
	},
	{//244
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	#if (USER/100)==12//用户标识:四川
	{//245 设置电表时间采集日期
		ADDR_AFN04F245,
		0xff,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		4,//数据长度
		0,//最大Pn
	},
	#else
	{//245
		0,
		0,//支持方案:B7=,B6=通信模块,B5=采集器,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
	},
	#endif
};

u32 Get_AFN04ParamterLib_MaxFn(void)
{
  return(sizeof(TerminalParamterLib)/sizeof(TerminalParamterLib_TypeDef));
}


void AFN04_Configure(void)//终端支持的参数配置,出口:数据在ADDR_DATABUFF
{
//ADDR_DATABUFF定义如下:
//第0Byte 支持的信息类组数n(0～31)	BIN	1
//第1Byte F1-F8
//第2Byte F9-F16
//第3Byte F17-F24
//...
	u32 i;
	u32 x;
	u32 y;
	u32 MaxFn;
	u8 *p8;
	
	p8=(u8*)(ADDR_DATABUFF);
	p8[0]=0;//支持的信息类组数n(0～31)=0
	x=0;
	y=0;
	MaxFn=(sizeof(TerminalParamterLib)/sizeof(TerminalParamterLib_TypeDef));
	for(i=0;i<MaxFn;i++)
	{
		if(TerminalParamterLib[i].project&(1<<(Project/100)))
		{
			if(TerminalParamterLib[i].PnType==p0Type)//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
			{
				y|=(1<<x);
			}
			else
			{
				if(TerminalParamterLib[i].PnMax!=0)
				{
					y|=(1<<x);
				}
			}
		}
		x++;
		if(x>=8)
		{
			p8[p8[0]+1]=y;
			p8[0]++;
			x=0;
			y=0;
		}
	}
	if(y!=0)
	{
		p8[p8[0]+1]=y;
		p8[0]++;
	}
}



