
#include "Project.h"
#include "Terminal_Uart_AFN05_Command.h"



//命令通信库
const TerminalCommandUartLib_TypeDef	TerminalCommandUartLib[]=
{
	{//遥控跳闸(控制轮次)
		ADDR_AFN05F1,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		MaxControlRound,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//允许合闸(控制轮次)
		ADDR_AFN05F2,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		MaxControlRound,//最大Pn
		0x0,//命令码0x0或0x55
	},
	{//F3
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//F4
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//F5
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//F6
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//F7
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//F8
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//时段功控投入(总加组号)
		ADDR_AFN05F9,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		2,//数据长度
		MaxTotalAddGroup,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//厂休功控投入(总加组号)	
		ADDR_AFN05F10,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		MaxTotalAddGroup,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//营业报停功控投入(总加组号)	
		ADDR_AFN05F11,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		MaxTotalAddGroup,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//当前功率下浮控投入(总加组号)
		ADDR_AFN05F12,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		8,//数据长度
		MaxTotalAddGroup,//最大Pn
		0x55,//命令码0x0或0x55
	},	
	{//F13
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//F14
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//月电控投入(总加组号)
		ADDR_AFN05F15,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		MaxTotalAddGroup,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//购电控投入(总加组号)
		ADDR_AFN05F16,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		MaxTotalAddGroup,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//时段功控解除(总加组号)
		ADDR_AFN05F17,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		2,//数据长度
		MaxTotalAddGroup,//最大Pn
		0x0,//命令码0x0或0x55
	},
	{//厂休功控解除(总加组号)
		ADDR_AFN05F18,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		MaxTotalAddGroup,//最大Pn
		0x0,//命令码0x0或0x55
	},
	{//营业报停功控解除(总加组号)
		ADDR_AFN05F19,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		MaxTotalAddGroup,//最大Pn
		0x0,//命令码0x0或0x55
	},
	{//当前功率下浮控解除(总加组号)
		ADDR_AFN05F20,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		8,//数据长度
		MaxTotalAddGroup,//最大Pn
		0x0,//命令码0x0或0x55
	},
	{//F21
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//F22
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//月电控解除(总加组号)
		ADDR_AFN05F23,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		MaxTotalAddGroup,//最大Pn
		0x0,//命令码0x0或0x55
	},
	{//购电控解除(总加组号)
		ADDR_AFN05F24,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		MaxTotalAddGroup,//最大Pn
		0x0,//命令码0x0或0x55
	},
	{//终端保电投入
		ADDR_AFN05F25,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//催费告警投入
		ADDR_AFN05F26,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//允许终端与主站通话
		ADDR_AFN05F27,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//终端剔除投入
		ADDR_AFN05F28,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//允许终端主动上报
		ADDR_AFN05F29,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//终端对电能表对时功能的开启与关闭
		ADDR_AFN05F30,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//对时命令
		ADDR_AFN05F31,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		6,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//中文信息
		ADDR_AFN05F32,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//终端保电解除
		ADDR_AFN05F33,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		0,//最大Pn
		0x0,//命令码0x0或0x55
	},
	{//催费告警解除
		ADDR_AFN05F34,
		0x08,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x0,//命令码0x0或0x55
	},
	{//禁止终端与主站通话
		ADDR_AFN05F35,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x0,//命令码0x0或0x55
	},
	{//终端剔除解除
		ADDR_AFN05F36,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x0,//命令码0x0或0x55
	},
	{//禁止终端主动上报
		ADDR_AFN05F37,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x0,//命令码0x0或0x55
	},
	{//激活终端连接主站
		ADDR_AFN05F38,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//命令终端断开连接
		ADDR_AFN05F39,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0xAA,//命令码0x0或0x55
	},
	{//F40
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//电容器控制投入(测量点号)
		ADDR_AFN05F41,
		0x14,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		2,//数据长度
		AFN05F41MaxPn,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//电容器控制切除(测量点号)
		ADDR_AFN05F42,
		0x14,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		pnType,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		2,//数据长度
		AFN05F42MaxPn,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//F43
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//F44
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//F45
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//F46
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//F47
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//F48
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,
		0,
		0,
		0,
	},
	{//命令指定通信端口暂停抄表
		ADDR_AFN05F49,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//命令指定通信端口恢复抄表
		ADDR_AFN05F50,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x0,//命令码0x0或0x55
	},
	{//命令指定通信端口重新抄表
		ADDR_AFN05F51,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//初始化指定通信端口下的全部中继路由信息
		ADDR_AFN05F52,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//删除指定通信端口下的全部电表
		ADDR_AFN05F53,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//F54
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F55
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F56
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F57删除指定事件代码ERC下的全部事件
		ADDR_AFN0EF3,
		0xff,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//F58
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F59
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F60
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F61
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F62
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F63
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F64
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F65
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F66
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F67
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F68
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F69
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F70
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F71
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F72
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F73
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F74
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F75
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F76
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F77
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F78
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F79
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F80
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F81
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F82
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F83
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F84
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F85
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F86
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F87
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F88
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F89
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F90
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F91
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F92
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F93
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F94
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F95
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F96
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F97
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F98
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F99
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F100
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F101
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F102
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F103
	#if (USER/100)==6//湖南系
		ADDR_AFN05F103,
		0xFF,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		3,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	#else
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	#endif
	},
	{//F104
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F105
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F106
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F107
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F108
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F109
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F110
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F111
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F112
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F113
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F114
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F115
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F116
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F117
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F118
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F119
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F120
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F121
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F122
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F123
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F124
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F125
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F126
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F127
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F128
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F129
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F130
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F131
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F132
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F133
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F134
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F135
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F136
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F137
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F138
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F139
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F140
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F141
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F142
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F143
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F144
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F145
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F146
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F147
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//F148
		0,
		0,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		0,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0,//命令码0x0或0x55
	},
	{//电能表通信参数自动维护功能开启与关闭
		ADDR_AFN05F149,
		0x24,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		1,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
	{//复位测量点参数变更标志
		ADDR_AFN05F150,
		0x24,//支持方案:B7=,B6=通信模块,B5=集中器Ⅱ型,B4=公变终端,B3=专变终端,B2=集中器,B1=网络表,B0=智能表
		p0Type,//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
		0,//数据长度
		0,//最大Pn
		0x55,//命令码0x0或0x55
	},
//AFN05F201上海已扩展使用
};



u32 Get_AFN05CommandLib_MaxFn(void)
{
	return(sizeof(TerminalCommandUartLib)/sizeof(TerminalCommandUartLib_TypeDef));
}

void AFN05_Configure(void)//终端支持的控制配置,出口:数据在ADDR_DATABUFF
{
//ADDR_DATABUFF定义如下:
//第0Byte 支持的信息类组数n(0～31)	BIN	1
//第1Byte F1-F8
//第2Byte F9-F16
//第3Byte F17-F24
//...
	u32 i;
	u32 x;
	u32 y;
	u32 MaxFn;
	u8 *p8;
	
	p8=(u8*)(ADDR_DATABUFF);
	p8[0]=0;//支持的信息类组数n(0～31)=0
	x=0;
	y=0;
	MaxFn=(sizeof(TerminalCommandUartLib)/sizeof(TerminalCommandUartLib_TypeDef));
	for(i=0;i<MaxFn;i++)
	{
		if(TerminalCommandUartLib[i].project&(1<<(Project/100)))
		{
			if(TerminalCommandUartLib[i].PnType==p0Type)//p0Type=终端信息点,pnType=测量点号,GnType=总加组号,CnType=电容器测量点号,DnType=直流模拟量号,RnType=控制轮次号,TnType=任务号,EnType=事件ERC号,MDCnType=电能表数据分级类号,MDEnType=电能表数据等级号
			{
				y|=(1<<x);
			}
			else
			{
				if(TerminalCommandUartLib[i].PnMax!=0)
				{
					y|=(1<<x);
				}
			}
		}
		x++;
		if(x>=8)
		{
			p8[p8[0]+1]=y;
			p8[0]++;
			x=0;
			y=0;
		}
	}
	if(y!=0)
	{
		p8[p8[0]+1]=y;
		p8[0]++;
	}
}













